### ISSUE TITLE
Video contains content from SME "ERROR"

### ISSUE THREAD

**Issue by mabdullah4** [Hatisoft/playyoutube-atom#5]
![image](https://user-images.githubusercontent.com/18432746/35194169-a5b0afdc-fed0-11e7-8b11-9a8e5c481c7c.png)
I added screenshot of the problem. Can you solve this problem..Plz? I love your package but sometimes I can't play some videos :-(

**Comment by alvarolorentedev** [comment]
yep this is an issue from youtube, cant do much :(
